#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjNzkA1+0k7QqU1QGYTkMeQAYlwRf/qm9ZzRDppCK+SzxAs4EfftodqmAt1+hEn3go5PMGiPEJlT2XaH6XAN0s0rdrOY5+S91/guiUdi/VwgQA2yD6vvafAysUoVnpcbhtzwWu983eafAgd0DkFPIxKM7KMzQZ7SLjVi57llattUgEinYNjl2lULDAlqYsh/MT7oeoWoXy5D8n12Ojkfy1895dBgz7aEPLFLH6bZ6NttFMmN7wKe8DrV8Va1c0vwSb0+PrD7UD65XH+AlUOP3oxPYk5yFOYkXhXWRTIQ9jjjFGmzybjHmSpI1bjeuKJdwNP32nGnIBjRh0f9nIGhWv tmccarthy
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjNzkA1+0k7QqU1QGYTkMeQAYlwRf/qm9ZzRDppCK+SzxAs4EfftodqmAt1+hEn3go5PMGiPEJlT2XaH6XAN0s0rdrOY5+S91/guiUdi/VwgQA2yD6vvafAysUoVnpcbhtzwWu983eafAgd0DkFPIxKM7KMzQZ7SLjVi57llattUgEinYNjl2lULDAlqYsh/MT7oeoWoXy5D8n12Ojkfy1895dBgz7aEPLFLH6bZ6NttFMmN7wKe8DrV8Va1c0vwSb0+PrD7UD65XH+AlUOP3oxPYk5yFOYkXhXWRTIQ9jjjFGmzybjHmSpI1bjeuKJdwNP32nGnIBjRh0f9nIGhWv core

users:
  - name: "user"
    passwd: "$6FMi11BJFsAc"
    groups:
      - "root"
